Repository FEniCS/ffcx, pull requests merged in 2025-02, with the labels that each got.

#745 Add check for coordinate element hash
  test/test_jit_forms.py
Labels: testing

#746 Add geometry element hash to `ufcx_expression`
  ffcx/codegeneration/C/expressions.py
  ffcx/codegeneration/C/expressions_template.py
  ffcx/codegeneration/C/integrals.py
  ffcx/codegeneration/ufcx.h
  ffcx/ir/representation.py
  test/test_jit_expression.py
Labels: enhancement

#733 Resolve jacobians from duplicate meshes
  ffcx/codegeneration/symbols.py
  test/test_jit_forms.py
Labels: bug, backport?
